/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.hpe.amce.mapping

/**
 * To be deleted.
 */
class Library {
    /**
     * To be deleted.
     * @return To be deleted.
     */
    boolean someLibraryMethod() {
        [].fla
        true
    }
}
